name: maxus-ai
favicon: null
layout_spectrum: 0.1435075211338699
typography_spectrum: 0.22347
title: Maxus - Artificial Intelligence Reports
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-47564584-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#002722'
    - '#fefefe'
    - '#4f6363'
    - '#a7b9b8'
  brandStrength: 0.0625
  lightness: 0.7073879963718355
  saturation: 0.75
  rhythmicContrast: 0.12595921801403165
purpose: []
